<a href="https://colab.research.google.com/github/yoonputer/Team_Project2/blob/master/Deeplearning/to_web.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!ls ./drive/MyDrive/Forkspoon/tok_index_word.pkl

./drive/MyDrive/Forkspoon/tok_index_word.pkl


In [ ]:
!python -m pip install konlpy

In [ ]:
!curl -O https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh

In [ ]:
!source ./mecab.sh

In [8]:
import tensorflow as tf

model = tf.keras.models.load_model('./drive/MyDrive/Forkspoon/test_dummy_LSTM.h5')
print(model)

In [10]:
import pickle
import sqlite3
import pandas as pd
import numpy as np
connect = sqlite3.connect('./drive/MyDrive/Forkspoon/db.sqlite3')

stopwords = pd.read_sql_query('select * from stopwords',connect)
ko_stopwords_list = np.array(stopwords['words'].tolist())

In [11]:
import konlpy
from konlpy.tag import Mecab
mecab= Mecab()

In [12]:
input_sentance= mecab.morphs('성실합니다')
input_sentance= [tok for tok in input_sentance if tok not in stopwords]
print(input_sentance)

['성실', '합니다']


In [13]:
tokenizer = pickle.load(open('./drive/MyDrive/Forkspoon/tokenizers.pkl','rb'))

In [14]:
vocb_size = len(tokenizer.word_index)
vocb_size

16343

In [15]:
encoded = tokenizer.texts_to_sequences([input_sentance])
encoded

pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=300)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [16]:
score = model.predict(pad_new)
score

array([[6.1978037e-03, 1.4306318e-03, 9.8902494e-01, 2.1841552e-03,
        9.8138291e-04, 1.4463159e-04, 1.9703866e-05, 1.6715152e-05]],
      dtype=float32)

In [17]:
import numpy as np

np.argmax(score)

2

## 함수로 만들기

In [18]:
# mecab = Mecab(dicpath=r"C:\mecab\mecab-ko-dic")
def sentance_predict(sentence):
  mecab= Mecab()
  input_sentance= mecab.morphs(sentence)
  input_sentance= [tok for tok in input_sentance if tok not in stopwords]
  encoded = tokenizer.texts_to_sequences([input_sentance])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=300)
  score = model.predict(pad_new)
  return score

In [19]:
sentencess = '성실하네요' 
sentance_predict(sentencess)


array([[1.4588406e-02, 2.2683085e-03, 9.7088313e-01, 1.0409605e-02,
        1.5200150e-03, 2.5400592e-04, 4.1573901e-05, 3.4901594e-05]],
      dtype=float32)